apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      restartPolicy: Always

      volumes:
        - name: notebooks
          hostPath:
            path: {{ .Values.volumes.hostPath }}
            type: DirectoryOrCreate

      containers:
        - name: jupyter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          command: ["sh", "-c", "start-notebook.sh --NotebookApp.token=${JUPYTER_PASSWORD}"]

          env:
            - name: CHOWN_EXTRA
              value: "/home/jovyan/work/"
            - name: CHOWN_EXTRA_OPTS
              value: "-R"
            - name: JUPYTER_ENABLE_LAB
              value: "yes"
            - name: JUPYTER_PASSWORD
              value: "{{ .Values.jupyter.password }}"
            - name: NEWS_DATA
              value: "/home/jovyan/work"

          securityContext:
            runAsUser: 0
            runAsGroup: 0

          volumeMounts:
            - name: notebooks
              mountPath: /home/jovyan/work

